### ISSUE TITLE
Feature Request via Inlight App

### ISSUE THREAD

**Issue by pitashi** [afty/TalkChain-iOS#1]
1. Closing TalkChain. It would be better to give possibility to our developers to close chat through code.
2. Not decrement badge numbers. When user taps on pushes from TalkChain budges counts should nullify. 
3. Remove status bar. In Inlight status bar is hidden from all screens, and it would be better to hide status bar from TalkChain too for correspondent with Inlight UI. 
4. When user signs out of Inlight TalkChain doesn't sign out. For example user sign in with “A” account and also sign in in TaklChain. Then user sign out and sign in with “B” account and sees TalkChain is signed in with “A” users account.

**Comment by cthomaschase** [comment]
Please make these into separate enhancement requests so we can track, comment and close each separately. Thanks.
