### ISSUE TITLE
On first login to talk chain app - bumps you back to host app (via Inlight app)

### ISSUE THREAD

**Issue by monika3** [afty/TalkChain-iOS#6]
Steps to reproduce: 

1. Delete and Redownload Inlight
2. Go to chat and sign in 
3. Bumps you out of chat and back to host app upon sign-in authentication

**Comment by cthomaschase** [comment]
I've seen this as well, looking into it.

**Comment by cthomaschase** [comment]
Fixed in 1.1.9
