### ISSUE TITLE
Photo doesn't select correctly on iPad

### ISSUE THREAD

**Issue by jazgab** [afty/TalkChain-iOS#7]
Can't create a new discussion on iPad version. After choosing photo in order to create discussion, it says please choose your photo. 

via Maysalward

**Comment by pitashi** [comment]
Today we do not support host apps that are built to support iPad natively (e.g. designed to fit the interface size of the iPad and set to run that way). Talkchain will not function properly and/or crash when loading screens in this way. 

Note however that if the host app is not set to run natively on Ipad, but works on iPad (e.g. the iPad shows the interface as the iPhone size with black empty space around it), then Talkchain will function like this properly.

We will be adding a function that checks if Talkchain is trying to be run on an iPad natively and will provide an elegant user error/message w/ no crash.
